### ISSUE TITLE
use modal

### ISSUE THREAD

**Issue by alikazemkhanloo** [wll8/redoc-try#21]
Hi,
I think it is better to have a modal to have a full-width swagger box. and scrolling wouldn't affect document's scroll position.

When trying an API, normally, the rest of the page is useless.

**Comment by wll8** [comment]
At present, the latest code can hide some elements that are repeated with redoc in swagger, but it does not support interface testing in the pop-up window. Maybe it would be better to have more space for testing, but how to design is a problem.

``` css
.swaggerBox:not(.onlySwagger) .swagger-ui .opblock .opblock-section-header,
.swaggerBox:not(.onlySwagger) .btn.cancel,
.swaggerBox:not(.onlySwagger) .try-out,
.swaggerBox:not(.onlySwagger) .responses-inner>div>h4,
.swaggerBox:not(.onlySwagger) :not(.live-responses-table).responses-table,
.swaggerBox:not(.onlySwagger) .opblock-body > .opblock-description-wrapper,
.swaggerBox:not(.onlySwagger) .swagger-ui .opblock-summary * {
  display: none;
}
```
